spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-lab/config-repo.git
          searchPaths: '{application}'
          force-pull: true

server:
  port: 8000